name = "idpusatmedia"
main = "_worker.js"
compatibility_date = "2023-05-26"

[[routes]]
pattern = "idpm.vpnyubi.biz.id"
custom_domain = true
[[routes]]
pattern = "updates.netflix.com.idpm.vpnyubi.biz.id"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.idpm.vpnyubi.biz.id"
custom_domain = true
[[routes]]
pattern = "img.email1.vidio.com.idpm.vpnyubi.biz.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.idpm.vpnyubi.biz.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.idpm.vpnyubi.biz.id"
custom_domain = true
[[routes]]
pattern = "ruangguru.com.com.idpm.vpnyubi.biz.id"
custom_domain = true
[[routes]]
pattern = "bakrie.ac.id.idpm.vpnyubi.biz.id"
custom_domain = true

[vars]
PROXYIP = "103.6.207.108:8080"
UUID = "6004d59a-8e09-4eeb-b9fd-7c5221ac7c55"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
