name = "idcayagan"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true
[[routes]]
pattern = "idcg.vpnyubi.biz.id"
custom_domain = true
[[routes]]
pattern = "updates.netflix.com.idcg.vpnyubi.biz.id"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.idcg.vpnyubi.biz.id"
custom_domain = true
[[routes]]
pattern = "img.email1.vidio.com.idcg.vpnyubi.biz.id"
custom_domain = true
[[routes]]
pattern = "www.udemy.com.idcg.vpnyubi.biz.id"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.idcg.vpnyubi.biz.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.idcg.vpnyubi.biz.id"
custom_domain = true
[[routes]]
pattern = "ir.huya.com.idcg.vpnyubi.biz.id"
custom_domain = true
[[routes]]
pattern = "investor.spotify.com.idcg.vpnyubi.biz.id"
custom_domain = true
[[routes]]
pattern = "app.genflix.co.id.idcg.vpnyubi.biz.id"
custom_domain = true
[[routes]]
pattern = "ruangguru.com.idcg.vpnyubi.biz.id"
custom_domain = true
[[routes]]
pattern = "space.byu.id.idcg.vpnyubi.biz.id"
custom_domain = true

[vars]
PROXYIP = "203.194.112.119:2053"
UUID = "6004d59a-8e09-4eeb-b9fd-7c5221ac7c55"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
